INSERT INTO categoria (id, nome, descricao) VALUES (1, 'Informática', 'Produtos de informática');
INSERT INTO categoria (id, nome, descricao) VALUES (2, 'Livros', 'Livros técnicos e educacionais');
INSERT INTO categoria (id, nome, descricao) VALUES (3, 'Eletrônicos', 'Aparelhos e dispositivos eletrônicos');
INSERT INTO categoria (id, nome, descricao) VALUES (4, 'Moda', 'Roupas, calçados e acessórios');
INSERT INTO categoria (id, nome, descricao) VALUES (5, 'Videogames', 'Jogos, consoles e acessórios para videogames');
INSERT INTO local (id, nome, endereço, capacidade) VALUES (1, 'Auditório Central', 'Rua das Flores, 100', 200);
INSERT INTO local (id, nome, endereço, capacidade) VALUES (2, 'Sala de Conferências', 'Avenida Brasil, 250', 100);
INSERT INTO local (id, nome, endereço, capacidade) VALUES (3, 'Centro de Eventos', 'Rua São Paulo, 500', 300);
INSERT INTO local (id, nome, endereço, capacidade) VALUES (4, 'Auditório de Tecnologia', 'Avenida Paulista, 800', 150);
INSERT INTO local (id, nome, endereço, capacidade) VALUES (5, 'Espaço Inovação', 'Rua das Palmeiras, 75', 80);
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (1, 'Carlos Almeida', 'Especialista em desenvolvimento de software e arquitetura de sistemas.', 'carlos.almeida@email.com');
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (2, 'Mariana Santos', 'Pesquisadora na área de inteligência artificial e aprendizado de máquina.', 'mariana.santos@email.com');
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (3, 'Ricardo Oliveira', 'Consultor especializado em gestão de projetos e metodologias ágeis.', 'ricardo.oliveira@email.com');
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (4, 'Fernanda Costa', 'Profissional especializada em segurança da informação e proteção de dados.', 'fernanda.costa@email.com');
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (5, 'Lucas Ferreira', 'Especialista em tecnologia, inovação e transformação digital.', 'lucas.ferreira@email.com');
INSERT INTO participante (id, nome, email, telefone) VALUES (1, 'João Silva', 'joao.silva@email.com', '(14) 99999-1111');
INSERT INTO participante (id, nome, email, telefone) VALUES (2, 'Ana Oliveira', 'ana.oliveira@email.com', '(14) 99999-2222');
INSERT INTO participante (id, nome, email, telefone) VALUES (3, 'Pedro Santos', 'pedro.santos@email.com', '(14) 99999-3333');
INSERT INTO participante (id, nome, email, telefone) VALUES (4, 'Juliana Costa', 'juliana.costa@email.com', '(14) 99999-4444');
INSERT INTO participante (id, nome, email, telefone) VALUES (5, 'Marcos Ferreira', 'marcos.ferreira@email.com', '(14) 99999-5555');
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (1, 'Workshop de Java', 'Workshop sobre desenvolvimento de aplicações com Java e Spring Boot', '2026-09-10 09:00:00', '2026-09-10 12:00:00', 50, 'AGENDADO', 1, 1, 1);
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (2, 'Introdução à Inteligência Artificial', 'Palestra sobre conceitos fundamentais de inteligência artificial', '2026-09-12 14:00:00', '2026-09-12 17:00:00', 80, 'AGENDADO', 1, 2, 2);
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (3, 'Gestão de Projetos', 'Evento sobre metodologias e boas práticas para gestão de projetos', '2026-09-15 09:00:00', '2026-09-15 16:00:00', 100, 'AGENDADO', 2, 3, 3);
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (4, 'Segurança da Informação', 'Palestra sobre segurança, privacidade e proteção de dados', '2026-09-18 19:00:00', '2026-09-18 21:30:00', 60, 'AGENDADO', 3, 4, 4);
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (5, 'Tecnologia e Inovação', 'Debate sobre tendências tecnológicas e inovação no mercado', '2026-09-20 10:00:00', '2026-09-20 13:00:00', 120, 'AGENDADO', 4, 5, 5);
INSERT INTO inscricao (id, data_inscricao, status, participante_id) VALUES (1, '2026-09-01 08:30:00', 'CONFIRMADA', 1);
INSERT INTO inscricao (id, data_inscricao, status, participante_id) VALUES (2, '2026-09-01 09:15:00', 'CONFIRMADA', 2);
INSERT INTO inscricao (id, data_inscricao, status, participante_id) VALUES (3, '2026-09-01 10:00:00', 'PENDENTE', 3);
INSERT INTO inscricao (id, data_inscricao, status, participante_id) VALUES (4, '2026-09-01 11:30:00', 'CONFIRMADA', 4);
INSERT INTO inscricao (id, data_inscricao, status, participante_id) VALUES (5, '2026-09-01 13:00:00', 'CANCELADA', 5);